import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import UserActions from '../redux/user'
import {useDispatch,useSelector} from 'react-redux'
import { useEffect,useState } from 'react'

export default function Home() {
  const dispatch = useDispatch()
  const states = useSelector(state => state.GetAllUsersState)
  const [users, setUsers] = useState('')

  useEffect(() => {
    if(states?.users?.data?.length > 0){
      console.log(states.users.data)
      setUsers(JSON.stringify(states.users.data, null, 2))
      console.log(users)
    }

  }, [states])
  

  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

			<main className={styles.main}>
				<h1>Bitzquad NextJS Template</h1>
			</main>

        <button onClick={() => dispatch(UserActions.GetAllUsers())}>Get All Users</button>

        <textarea rows={25} cols={100} value={users} readOnly></textarea>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    </>
  )
}
